version: '3.8'
services:
  database:
    container_name: "simple-app-db"
    image: "postgres:15.2-alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=database
    volumes:
      - ".docker/database:/var/lib/postgresql/data"

  api:
    container_name: "simple-app-api"
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
networks:
  default:
    driver: bridge
    name: simple-app-network
